///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
// ignore_for_file: avoid_function_literals_in_foreach_calls

class UserModelRolesParams {
/*
{} 
*/

  // ignore: empty_constructor_bodies
  UserModelRolesParams.fromJson(Map<String, dynamic> json) {}
  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = <String, dynamic>{};
    return data;
  }
}

class UserModelRoles {
/*
{
  "searchValue": null,
  "createBy": "admin",
  "createTime": "2018-03-16 11:33:00",
  "updateBy": null,
  "updateTime": null,
  "remark": "普通角色",
  "pageNum": null,
  "pageSize": null,
  "orderBy": null,
  "params": {},
  "roleId": 2,
  "roleName": "普通角色2",
  "roleKey": "common",
  "roleSort": "2",
  "dataScope": "2",
  "status": "0",
  "delFlag": "0",
  "flag": true,
  "menuIds": null,
  "startTime": null,
  "endTime": null,
  "admin": false
} 
*/

  String? searchValue;
  String? createBy;
  String? createTime;
  String? updateBy;
  String? updateTime;
  String? pageNum;
  String? pageSize;
  String? orderBy;
  String? remark;
  UserModelRolesParams? params;
  int? roleId;
  String? roleName;
  String? roleKey;
  String? roleSort;
  String? dataScope;
  String? status;
  String? delFlag;
  bool? flag;
  String? menuIds;
  String? startTime;
  String? endTime;
  bool? admin;

  UserModelRoles({
    this.searchValue,
    this.createBy,
    this.createTime,
    this.updateBy,
    this.updateTime,
    this.remark,
    this.pageNum,
    this.pageSize,
    this.orderBy,
    this.params,
    this.roleId,
    this.roleName,
    this.roleKey,
    this.roleSort,
    this.dataScope,
    this.status,
    this.delFlag,
    this.flag,
    this.menuIds,
    this.startTime,
    this.endTime,
    this.admin,
  });
  UserModelRoles.fromJson(Map<String, dynamic> json) {
    searchValue = json["searchValue"]!.toString();
    createBy = json["createBy"]!.toString();
    createTime = json["createTime"]!.toString();
    updateBy = json["updateBy"]!.toString();
    updateTime = json["updateTime"]!.toString();
    remark = json["remark"]!.toString();
    pageNum = json["pageNum"]!.toString();
    pageSize = json["pageSize"]!.toString();
    orderBy = json["orderBy"]!.toString();
    params = json["params"] != null
        ? UserModelRolesParams.fromJson(json["params"])
        : null;
    roleId = json["roleId"]?.toInt();
    roleName = json["roleName"]?.toString();
    roleKey = json["roleKey"]?.toString();
    roleSort = json["roleSort"]?.toString();
    dataScope = json["dataScope"]?.toString();
    status = json["status"]?.toString();
    delFlag = json["delFlag"]?.toString();
    flag = json["flag"];
    menuIds = json["menuIds"]?.toString();
    startTime = json["startTime"]?.toString();
    endTime = json["endTime"]?.toString();
    admin = json["admin"];
  }
  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = <String, dynamic>{};
    data["searchValue"] = searchValue;
    data["createBy"] = createBy;
    data["createTime"] = createTime;
    data["updateBy"] = updateBy;
    data["updateTime"] = updateTime;
    data["remark"] = remark;
    data["pageNum"] = pageNum;
    data["pageSize"] = pageSize;
    data["orderBy"] = orderBy;
    if (params != null) {
      data["params"] = params!.toJson();
    }
    data["roleId"] = roleId;
    data["roleName"] = roleName;
    data["roleKey"] = roleKey;
    data["roleSort"] = roleSort;
    data["dataScope"] = dataScope;
    data["status"] = status;
    data["delFlag"] = delFlag;
    data["flag"] = flag;
    data["menuIds"] = menuIds;
    data["startTime"] = startTime;
    data["endTime"] = endTime;
    data["admin"] = admin;
    return data;
  }
}

class UserModel {
/*
{
  "userId": 1,
  "companyId": 100,
  "loginName": "admin",
  "userName": "超级管理员",
  "email": "bingo@163.com",
  "phonenumber": "15888888888",
  "sex": "0",
  "avatar": "/profile/avatar/2020/07/16/a1a19b598293d92dab54ffbaffc925e9.png",
  "roles": [
    {
      "searchValue": null,
      "createBy": "admin",
      "createTime": "2018-03-16 11:33:00",
      "updateBy": null,
      "updateTime": null,
      "remark": "普通角色",
      "pageNum": null,
      "pageSize": null,
      "orderBy": null,
      "params": {},
      "roleId": 2,
      "roleName": "普通角色2",
      "roleKey": "common",
      "roleSort": "2",
      "dataScope": "2",
      "status": "0",
      "delFlag": "0",
      "flag": true,
      "menuIds": null,
      "startTime": null,
      "endTime": null,
      "admin": false
    }
  ]
} 
*/

  int? userId;
  int? companyId;
  String? loginName;
  String? userName;
  String? email;
  String? phonenumber;
  String? sex;
  String? avatar;
  List<UserModelRoles>? roles;

  UserModel({
    this.userId,
    this.companyId,
    this.loginName,
    this.userName,
    this.email,
    this.phonenumber,
    this.sex,
    this.avatar,
    this.roles,
  });
  UserModel.fromJson(Map<String, dynamic> json) {
    userId = json["userId"]!.toInt();
    companyId = json["companyId"]!.toInt();
    loginName = json["loginName"]!.toString();
    userName = json["userName"]!.toString();
    email = json["email"]!.toString();
    phonenumber = json["phonenumber"]!.toString();
    sex = json["sex"]!.toString();
    avatar = json["avatar"]!.toString();
    if (json["roles"] != null) {
      final v = json["roles"];
      final arr0 = <UserModelRoles>[];
      v.forEach((v) {
        arr0.add(UserModelRoles.fromJson(v));
      });
      roles = arr0;
    }
  }
  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = <String, dynamic>{};
    data["userId"] = userId;
    data["companyId"] = companyId;
    data["loginName"] = loginName;
    data["userName"] = userName;
    data["email"] = email;
    data["phonenumber"] = phonenumber;
    data["sex"] = sex;
    data["avatar"] = avatar;
    if (roles != null) {
      final v = roles;
      final arr0 = [];
      v!.forEach((v) {
        arr0.add(v.toJson());
      });
      data["roles"] = arr0;
    }
    return data;
  }
}
